spring:
  application:
    name: product-server
server:
  port: 7002
  servlet:
    context-path: /product

eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:3333/eureka/eureka
    register-with-eureka: true
    fetch-registry: true