
server:
  servlet:
    context-path: /consumer
  port: 7004
spring:
  application:
    name: consumer-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3333/eureka/eureka
